# ## Todo
# ### 全件取得
# GET http://localhost:3002/todo

# ### 1件追加
# POST http://localhost:3002/todo
# Content-Type: application/json

# {
#   "title": "sample2",
#   "status": "waiting"
# }

# ### 1件更新
# PUT http://localhost:3002/todo
# Content-Type: application/json

# {
#   "id": ":id",
#   "title": "test update",
#   "status": "done"
# }

# ### 1件削除
# DELETE http://localhost:3002/todo/:id



## Company
POST http://localhost:3002/company
Content-Type: application/json

{
  "companyName": "株式会社NFTDrive",
  "prtimesUrl": "https://prtimes.jp/main/html/rd/p/000000003.000119487.html",
  "email": "nftdrive01@gmail.com",
  "chargeEmployee": "中島理男",
  "category": "アプリ"
}
